services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mediadreams\MdUnreadnews\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Mediadreams\MdUnreadnews\Command\Cleanup:
    tags:
      - name: 'console.command'
        command: 'mdUnreadnews:cleanup'
        description: 'Remove old unread information from news records'
        # not required, defaults to false
        hidden: false
